### ISSUE TITLE
WpfTheory with MemberData parameters deserialization failure

### ISSUE THREAD

**Issue by GerardHindiye** [AArnott/Xunit.StaFact#11] opened 2018-08-20 09:44 UTC
Hello,

After updating our WPF project XUnit version for test cases, a lot of tests started failing due to STA Threads. Installing StaFact library and using WpfFact and WpfTheory helped a lot in solving those issues.

However, after converting some of our Theory to WpfTheory, some of them that contains MemberData objects provided started to fail to run giving the following exception: 
------ Run test started ------
[xUnit.net 00:00:05.4308436] IPC.POS.Tests: Test case ScreenBaseTest.ScreenBaseTest_SetBrandMenuEnabled failed to deserialize: Test case deserialization failure: System.InvalidOperationException: Could not de-serialize type 'Xunit.Sdk.WpfTheoryTestCase' because it lacks a parameterless constructor.
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value)
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value)
   at Xunit.Sdk.TestCaseBulkDeserializer.Deserialize(ITestFrameworkDiscoverer discoverer, ITestFrameworkExecutor executor, String serialization)
[xUnit.net 00:00:14.8414221]   Starting:    Tests
[xUnit.net 00:00:15.0974942]   Finished:    Tests
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.
========== Run test finished: 0 run (0:00:24.1873834) ==========

If i revert to using Theory, I can see that the parameters are deserialized correctly and unit test run, but using WpfTheory gives me the mentioned exception for same objects provided and unit test is not run.

Any feedback would be appreciated.

Thanks.

**Comment by Serg046** [comment] 2019-01-28 23:05
I am not an owner but let me try to understand the issue.
I believe [this line](https://github.com/xunit/xunit/blob/9d10262a3694bb099ddd783d735aba2a7aac759d/src/common/XunitSerializationInfo.cs#L213) throws an exception. The line is inside `DeserializeSerializable` method which is most probably called [from here](https://github.com/xunit/xunit/blob/9d10262a3694bb099ddd783d735aba2a7aac759d/src/common/XunitSerializationInfo.cs#L110). It means `WpfTheoryTestCase` and other test cases should contain parameterless constructor. Also there is some helpful comment inside the base `XunitTheoryTestCase` class. Its parameterless constructor is marked by `ObsoleteAttribute`:
```csharp
[Obsolete("Called by the de-serializer; should only be called by deriving classes for de-serialization purposes")]
public XunitTheoryTestCase();
```
Of course, we can just add parameterless constructor for all test cases but it would be better to understand your case. Could you describe it and help to reproduce?

**Comment by Serg046** [comment] 2019-02-01 21:55
Can be related https://github.com/xunit/xunit/issues/1742

**Comment by AArnott** [comment] 2019-02-05 06:05
Adding the default constructor to this type is fine. But can you please give me the repro steps so I can verify the problem and the fix?

**Comment by GerardHindiye** [comment] 2019-02-05 09:34
In my case, it was a test case that contains an STA thread and we are doing the test case as follows:
  
        [WpfTheory]
        [MemberData(nameof(TestData))]
        public void SurpriseDelightGridHeightTest(DateTime outDate, DateTime nowDate, bool 
           expectedResult)
        {
           //Test case logic
        }


        public static IEnumerable<object[]> TestData
        {
            get
            {
                yield return new object[] { DateTime.Now, DateTime.Now.AddMinutes(2), true };
                yield return new object[] { DateTime.Now, DateTime.Now.AddMinutes(-3), false };
                yield return new object[] { DateTime.Now, DateTime.Now, false };
            }
        }

**Comment by AArnott** [comment] 2019-02-05 15:17
And how do you run this test where it fails? I just tried Test Explorer and xunit.console and the 3 test cases all ran for me.

**Comment by GerardHindiye** [comment] 2019-02-06 11:05
Since it has been like 6 months after i faced the issue, we have moved away from using StaFact library. And we fixed the tests using another approach. So I am trying to reproduce it but i am unable to do so.

**Comment by AArnott** [comment] 2019-02-06 16:19
OK, thanks for following up. I'll close this since we have no repro then.

**Closed by AArnott** 2019-02-06 16:19 UTC
Labels: bug, help wanted
